#!/usr/bin/python3
from gi import require_version
require_version('Notify', '0.7')
require_version('Gtk', '3.0')
require_version('GSound', '1.0')
from gi.repository import Notify, GLib, Gtk, GSound
from subprocess import Popen, PIPE
from time import sleep
import os, re, sys
from shutil import which
from icalendar import Todo

class Tasks:
    def __init__(self):
        self.tasks = []
        self.task_file = os.path.expanduser('~/.local/share/evolution/tasks/system/tasks.ics')

    def __load_tasks(self, task_file):
        if os.path.exists(task_file):
            with open(task_file, 'r') as tf:
                data = Todo.from_ical(tf.read())
                self.tasks = [item for item in data.walk('VTODO') if (('PERCENT-COMPLETE' in item.keys() and item['PERCENT-COMPLETE'] != 100) or 'PERCENT-COMPLETE' not in item.keys()) and 'PRIORITY' in item.keys()]

    def highest_priority(self):
        self.__load_tasks(self.task_file)
        if len(self.tasks) == 0:
            return None
        item = self.tasks[0]
        for i in self.tasks[1:]:
            if i['PRIORITY'] > item['PRIORITY']:
                item = i
        return item['SUMMARY']

class SystrayTask:
    def __init__(self, tasks):
        self.tasks = tasks
        self.tray = Gtk.StatusIcon()
        self.tray.set_from_stock(Gtk.STOCK_ADD)
        self.tray.connect('popup-menu', self.on_right_click)

    def on_right_click(self, icon, event_button, event_time):
        self.make_menu(event_button, event_time)

    def make_menu(self, event_button, event_time):
        menu = Gtk.Menu()

        # Add a task
        change = Gtk.MenuItem(label="Change task")
        change.show()
        menu.append(change)
        change.connect('activate', self.change)

        # add quit item
        quit = Gtk.MenuItem(label="Quit")
        quit.show()
        menu.append(quit)
        quit.connect('activate', sys.exit)

        menu.popup(None, None, self.tray.position_menu, self.tray, event_button, event_time)

    def change(self, menu_item):
        self.tasks.cancel_timeout()
        self.tasks.prompt_timeout()

class TaskNotify:
    def __init__(self):
        self.sound_ctx = GSound.Context()
        self.sound_ctx.init()
        self.count = 1
        self.pomodoro_length = 25
        self.tick_counter = self.pomodoro_length * 4 # ticks play for 15 seconds
        Notify.init('Task Tracker')
        self.notifications = []
        self.windows = []
        self.work = []
        self.tasks = Tasks()
        self.timeout_id = None
        self.prompt_timeout()

    def pomodoro(self):
        time = 15 if self.count % 4 == 0 else 5
        self.count += 1
        self.notifications.append(Notify.Notification.new('Tasks', 'Take a %d minute break' % time))
        notify = self.notifications[-1]
        notify.set_urgency(2)
        notify.set_timeout(time*60*1000)
        notify.show()
        self.timeout_id = GLib.timeout_add_seconds(time*60, self.prompt_timeout)
        return False

    def cancel_timeout(self):
        if self.timeout_id is not None:
            GLib.source_remove(self.timeout_id)
            self.tick_counter = 0
        self.timeout_id = None

    def prompt_timeout(self):
        self.sound_ctx.play_simple({GSound.ATTR_EVENT_ID : "complete",
                                    GSound.ATTR_CANBERRA_VOLUME: "0.1"})
        if len(self.notifications) > 0:
            self.notifications.pop()
        self.load_work()
        next_task = self.tasks.highest_priority()
        if len(self.work) > 0:
            self.request_work(self.work[0])
        elif next_task:
            self.suggest_task(next_task)
        else:
            self.request_task()
        self.timeout_id = GLib.timeout_add_seconds(self.pomodoro_length*60, self.pomodoro)
        self.tick_clock()
        return False

    def tick_clock(self, *args):
        if self.tick_counter > 0:
            self.tick_counter -= 1
            self.sound_ctx.play_full({GSound.ATTR_EVENT_ID : "clock",
                                      GSound.ATTR_CANBERRA_VOLUME: "0.1"},
                                      callback=self.tick_clock)
        else:
            self.tick_counter = self.pomodoro_length * 4

    def __parse_rerc(self, rerc):
        m = re.findall('BULLET\s*=>\s*[\'"]\s*(.)\s*[\'"]\s*,', open(rerc, 'r').read())
        if len(m) > 0:
            return m[-1]
        else:
            return '-'

    def __dump_re(self):
        env = os.environ
        env['EDITOR'] = which('cat')
        out, _ = Popen([which('re')], stdout=PIPE).communicate()
        return '\n'.join(out.decode().split('\n')[1:])

    def load_work(self):
        out = self.__dump_re()
        if os.path.exists('~/.rerc'):
            bullet = self.__parse_rerc('~/.rerc')
        elif os.path.exists('/etc/rerc'):
            bullet = self.__parse_rerc('/etc/rerc')
        self.work = [line.strip()[1:].strip() for line in out.split('\n') if len(line.strip()) > 0 and line.strip()[0] == bullet]

    def HandleDoNothing(self, obj, name):
        self.notifications.pop()

    def HandleEditTask(self, obj, name):
        self.notifications.pop()
        self.__modify_re('Modify', self.__dump_re())

    def HandleFinishedTask(self, obj, name):
        self.notifications.pop()
        next_task = self.tasks.highest_priority()
        if next_task:
            self.suggest_task(next_task)
        else:
            self.request_task()

    def HandleAddTask(self, obj, name):
        self.notifications.pop()
        self.__modify_re('Add', '', append=True)

    def HandleSelectTask(self, obj, name, summary):
        self.notifications.pop()
        self.__modify_re('Add', summary, append=True)

    def __save_re(self, obj, append, textbuffer):
        s = textbuffer.get_start_iter()
        e = textbuffer.get_end_iter()
        text = textbuffer.get_text(s, e, True)
        if append:
            text = text.replace('\n', ' ').strip()
            Popen([which('re'), text], stdout=PIPE, stderr=PIPE).wait()
        else:
            # Get the filename
            env = os.environ
            env['EDITOR'] = which('echo')
            out, _ = Popen([which('re')], env=env, stdout=PIPE, stderr=PIPE).communicate()
            fname = out.decode().strip().split('\n')[-1].strip()
            with open(fname, 'w') as f:
                f.write(text)

    def __modify_re(self, title, text, append=False):
        self.windows.append(Gtk.Window())
        win = self.windows[-1]
        win.set_default_size(500, 350)
        win.connect("destroy", Gtk.main_quit)
        win.set_border_width(5)

        # Header
        hb = Gtk.HeaderBar()
        hb.set_show_close_button(True)
        hb.props.title = 'Task Tracker - %s' % title
        win.set_titlebar(hb)
        save = Gtk.Button()
        save.set_label('Save')
        hb.pack_end(save)

        # Main Document
        scrolledwindow = Gtk.ScrolledWindow()
        scrolledwindow.set_hexpand(True)
        scrolledwindow.set_vexpand(True)
        win.add(scrolledwindow)
        textview = Gtk.TextView()
        textview.set_wrap_mode(Gtk.WrapMode.WORD)
        textbuffer = textview.get_buffer()
        textbuffer.set_text(text)
        save.connect('clicked', self.__save_re, append, textbuffer)
        scrolledwindow.add(textview)
        win.show_all()
        self.load_work()

    def suggest_task(self, summary):
        self.notifications.append(Notify.Notification.new('Tasks', 'This is the next priority task:\n' + summary))
        notify = self.notifications[-1]
        notify.add_action('select', 'Select', self.HandleSelectTask, summary)
        notify.add_action('addtask', 'Add Task', self.HandleAddTask)
        notify.set_urgency(2)
        notify.set_timeout(0)
        notify.show()

    def request_task(self):
        self.notifications.append(Notify.Notification.new('Tasks', 'What are you working on?'))
        notify = self.notifications[-1]
        notify.add_action('addtask', 'Add Task', self.HandleAddTask);
        notify.set_urgency(2)
        notify.set_timeout(0)
        notify.show()

    def request_work(self, summary):
        self.notifications.append(Notify.Notification.new('Tasks', 'Are you still working on this task?\n' + summary))
        notify = self.notifications[-1]
        notify.add_action('yes', 'Yes', self.HandleDoNothing)
        notify.add_action('view', 'View', self.HandleEditTask)
        notify.add_action('finish', 'Finish', self.HandleFinishedTask)
        notify.set_urgency(2)
        notify.set_timeout(0)
        notify.show()

if __name__ == '__main__':
    tasks = TaskNotify()
    SystrayTask(tasks)
    GLib.MainLoop().run()
